Repository nonmilk/coffee-grinder, pull requests merged in 2024-12, with the labels that each got.

#1 build: initial module-info and build script
  lib/build.gradle.kts
  lib/src/main/java/module-info.java
Labels: enhancement

#3 feat/camera: fix package structure
  lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/Camera.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/CameraMatrix.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/CameraOrientation.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/ClippingBox.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/OrthographicCamera.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/OrthographicView.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/PerspectiveCamera.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/PerspectiveView.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/math/Floats.java
Labels: bug

#4 feat/camera: views
  lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/CameraMatrix.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/OrthographicCamera.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/OrthographicView.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/PerspectiveCamera.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/PerspectiveView.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/view/OrthographicView.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/view/PerspectiveView.java
Labels: enhancement

#6 feat/clipping-box: refactor
  lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/Camera.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/CameraMatrix.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/ClippingBox.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/OrthographicCamera.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/PerspectiveCamera.java
Labels: bug, enhancement

#5 refactor(camera)!: make ClippingBox a class
  lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/Camera.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/CameraMatrix.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/ClippingBox.java
Labels: enhancement

#8 chore: IDEA config
  .idea/.gitignore
  .idea/compiler.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/vcs.xml
Labels: enhancement

#9 feat/camera-orientation: style and setters
  lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/CameraOrientation.java
Labels: bug

#7 refactor(camera)!: make CameraOrientation a class
  lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/Camera.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/CameraMatrix.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/CameraOrientation.java
Labels: enhancement

#10 chore: add Helix config
  .helix/languages.toml
Labels: enhancement

#2 feat/camera
  lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/Camera.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/Clippable.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/ClippingBox.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/Orientation.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/OrthographicCamera.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/PerspectiveCamera.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/view/OrthographicView.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/view/PerspectiveView.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/math/Floats.java
Labels: enhancement

#12 fix: correct view matrix
  lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/Orientation.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/OrthographicCamera.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/PerspectiveCamera.java
Labels: bug

#13 fix: handling polygons parallel to XY
  lib/src/main/java/io/github/nonmilk/coffee/grinder/Model.java
Labels: bug

#14 feat: implement z-buffer
  lib/src/main/java/io/github/nonmilk/coffee/grinder/render/ZBuffer.java
Labels: enhancement

#15 feat: TexturedTriangle basic setup
  lib/src/main/java/io/github/nonmilk/coffee/grinder/math/Vec3f.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/render/TexturedFiller.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/render/TexturedTriangle.java
Labels: enhancement

#16 build: transitive dependencies
  lib/src/main/java/module-info.java
Labels: enhancement

#17 build: fix module-info
  lib/src/main/java/module-info.java
Labels: enhancement

#18 chore: bump jshaper to 0.10.2
  lib/build.gradle.kts
  lib/src/main/java/io/github/nonmilk/coffee/grinder/Model.java
Labels: type/chore, type/style, type/refactor

#19 feat: implement z-buffer
  lib/build.gradle.kts
  lib/src/main/java/io/github/nonmilk/coffee/grinder/Renderer.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/render/TexturedFiller.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/render/TexturedTriangle.java
Labels: type/fix, type/feat, type/chore, type/refactor

#20 refactor: remove unused
  lib/src/main/java/io/github/nonmilk/coffee/grinder/Model.java
Labels: type/fix, type/feat, type/refactor

#21 build: sync with module-info
  lib/build.gradle.kts
  lib/src/main/java/module-info.java
Labels: type/build, type/style

#22 feat: diffuse lighting
  lib/src/main/java/io/github/nonmilk/coffee/grinder/Model.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/Renderer.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/math/Floats.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/math/UnitVec3f.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/math/Vec4f.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/render/RenderedFace.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/render/ScreenTransform.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/render/TexturedFiller.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/render/TexturedTriangle.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/render/triangle/Lighting.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/render/triangle/Normal.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/render/triangle/Shape.java
Labels: type/fix, type/feat, type/refactor

#23 feature: affine transforms
  lib/build.gradle.kts
  lib/dependencies/.gitignore
  lib/dependencies/Graphic_Conveyor-1.1.0.jar
  lib/src/main/java/io/github/nonmilk/coffee/grinder/transformations/ModelTransformer.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/transformations/RotationOrder.java
  lib/src/main/java/module-info.java
Labels: type/fix, type/feat, type/chore, type/build, type/refactor

#25 feat: affine library
  lib/build.gradle.kts
  lib/src/main/java/io/github/nonmilk/coffee/grinder/math/affine/AffineTransformation.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/math/affine/DataList.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/math/affine/Rotator.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/math/affine/Scaling.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/math/affine/Transformation.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/math/affine/Translator.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/math/affine/package-info.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/transformations/ModelTransformer.java
  lib/src/main/java/module-info.java
Labels: type/feat
