Repository nonmilk/coffee-grinder, pull requests merged in 2025-01, with the labels that each got.

#26 style: remove tab
  lib/src/main/java/io/github/nonmilk/coffee/grinder/Model.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/Renderer.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/Orientation.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/render/ColorTexture.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/render/ImageTexture.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/render/RenderedFace.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/render/Texture.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/render/TexturedFiller.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/render/triangle/UV.java
  lib/src/main/java/module-info.java
Labels: type/feat

#27 chore: bump dependencies
  lib/build.gradle.kts
  lib/src/main/java/io/github/nonmilk/coffee/grinder/Model.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/Renderer.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/math/Vec3f.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/math/Vec4f.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/render/ColorTexture.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/render/ImageTexture.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/render/RenderedFace.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/render/Texture.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/render/TexturedFiller.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/render/triangle/Normal.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/render/triangle/Shape.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/render/triangle/UV.java
Labels: type/chore

#28 fix: normalize camera x
  lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/Orientation.java
Labels: type/fix

#30 feat(Scene)!: remove camera list
  lib/src/main/java/io/github/nonmilk/coffee/grinder/Renderer.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/render/Scene.java
Labels: type/feat, breaking-change

#31 docs(transformations): add docs
  lib/src/main/java/io/github/nonmilk/coffee/grinder/transformations/ModelTransformer.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/transformations/RotationOrder.java
Labels: type/docs

#33 chore: upd math dependencies
  lib/build.gradle.kts
  lib/dependencies/.gitignore
  lib/dependencies/Graphic_Conveyor-1.1.0.jar
  lib/src/main/java/io/github/nonmilk/coffee/grinder/math/UnitVec3f.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/math/Vec2f.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/math/Vec3f.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/math/Vec4f.java
Labels: type/chore, type/build

#34 refactor: use compatible structure
  lib/src/main/java/io/github/nonmilk/coffee/grinder/Mesh.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/MeshFace.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/Model.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/RenderingPipeline.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/render/RenderedFace.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/render/triangle/Normal.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/render/triangle/Shape.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/render/triangle/UV.java
Labels: type/feat, type/refactor

#35 refactor(Model)!: change method signatures
  lib/src/main/java/io/github/nonmilk/coffee/grinder/Model.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/RenderingPipeline.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/transformations/ModelTransformer.java
Labels: type/refactor, breaking-change

#36 feat(transforms): transform functionality in model
  lib/build.gradle.kts
  lib/src/main/java/io/github/nonmilk/coffee/grinder/Model.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/render/triangle/Normal.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/transformations/ModelTransformer.java
Labels: type/feat, type/chore

#37 refactor!: ImageTexture rework
  lib/src/main/java/io/github/nonmilk/coffee/grinder/render/ImageTexture.java
Labels: type/feat, type/refactor, breaking-change

#39 chore: bump linear-algebra to 2.1.0
  lib/build.gradle.kts
Labels: type/chore

#40 chore: bump linear-algebra to v2.1.2
  lib/build.gradle.kts
Labels: type/fix, type/build

#42 refactor: remove unnecessary floor
  lib/src/main/java/io/github/nonmilk/coffee/grinder/render/ImageTexture.java
Labels: type/fix, type/refactor

#43 fix: correct orientation in space
  lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/Orientation.java
Labels: type/fix

#44 feat(model transformer): upd api
  lib/src/main/java/io/github/nonmilk/coffee/grinder/math/affine/Rotator.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/transformations/ModelTransformer.java
Labels: type/feat

#45 fix: offset pixel indexing by 1
  lib/src/main/java/io/github/nonmilk/coffee/grinder/render/ImageTexture.java
Labels: type/fix

#46 feat: clip when dimensions exceed allowed
  lib/src/main/java/io/github/nonmilk/coffee/grinder/RenderingPipeline.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/render/TexturedFiller.java
Labels: type/feat, type/refactor

#48 feat: vertex selection
  lib/src/main/java/io/github/nonmilk/coffee/grinder/Renderer.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/RenderingPipeline.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/render/TexturedFiller.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/render/triangle/Shape.java
Labels: type/fix, type/feat, type/refactor

#47 fix: adapt to screen
  lib/src/main/java/io/github/nonmilk/coffee/grinder/RenderingPipeline.java
Labels: type/fix, type/style

#49 test: init tests
  lib/build.gradle.kts
Labels: type/chore, type/build, type/ci

#51 feat: expose rendering settings
  lib/src/main/java/io/github/nonmilk/coffee/grinder/Renderer.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/RenderingPipeline.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/render/TexturedFiller.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/render/Wireframe.java
Labels: type/feat

#52 docs(PerspectiveView): javadoc from existing comments
  lib/src/main/java/io/github/nonmilk/coffee/grinder/camera/view/PerspectiveView.java
Labels: type/fix, type/docs

#53 fix(ZBuffer): don't raise an exception
  lib/src/main/java/io/github/nonmilk/coffee/grinder/render/ZBuffer.java
Labels: type/fix

#54 refactor!: use obj triplets instead of vertices
  lib/src/main/java/io/github/nonmilk/coffee/grinder/Renderer.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/RenderingPipeline.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/render/TexturedFiller.java
  lib/src/main/java/io/github/nonmilk/coffee/grinder/render/ZBuffer.java
Labels: type/feat, type/refactor, breaking-change

#56 test(screen transforms): some tests for screen transformation process
  lib/src/test/java/io/github/nonmilk/coffee/grinder/camera/TestClippingBox.java
  lib/src/test/java/io/github/nonmilk/coffee/grinder/camera/TestOrthographicCamera.java
  lib/src/test/java/io/github/nonmilk/coffee/grinder/camera/TestPerspectiveCamera.java
  lib/src/test/java/io/github/nonmilk/coffee/grinder/camera/view/TestOrthographicView.java
  lib/src/test/java/io/github/nonmilk/coffee/grinder/camera/view/TestPerspectiveView.java
Labels: type/chore

#55 feat: vertex deletion
  lib/src/main/java/io/github/nonmilk/coffee/grinder/Model.java
Labels: type/feat

#57 fix: triplet deletion
  lib/src/main/java/io/github/nonmilk/coffee/grinder/Model.java
Labels: type/fix

#58 build: add all packages to module-info
  lib/src/main/java/module-info.java
Labels: type/build
